name: Self-Hosted runner CI with Gradle

on: [ push ]

jobs:
  selfhost-build:
    if: github.repository_owner == 'FlashyReese'
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          check-latest: true
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload Auild Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'Sodium Extra Artifacts'
          path: build/libs
